const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { buildSync } = require('esbuild');

const rootDir = path.resolve(__dirname, '..');
const vendorDir = path.join(rootDir, 'src', 'vendor');
const licenseDir = path.join(vendorDir, 'licenses');

fs.mkdirSync(licenseDir, { recursive: true });

const assets = [
  ['chart.js', 'dist/chart.umd.js', 'chart.umd.js'],
  ['hammerjs', 'hammer.min.js', 'hammer.min.js'],
  ['chartjs-plugin-zoom', 'dist/chartjs-plugin-zoom.min.js', 'chartjs-plugin-zoom.min.js'],
  ['mqtt', 'dist/mqtt.min.js', 'mqtt.min.js']
];

const licenses = [
  ['chart.js', 'LICENSE.md', 'chart.js-LICENSE.md'],
  ['hammerjs', 'LICENSE.md', 'hammerjs-LICENSE.md'],
  ['chartjs-plugin-zoom', 'LICENSE.md', 'chartjs-plugin-zoom-LICENSE.md'],
  ['mqtt', 'LICENSE.md', 'mqtt-LICENSE.md']
];

function packageDir(name) {
  let current = path.dirname(require.resolve(name, { paths: [rootDir] }));
  while (current !== path.dirname(current)) {
    const metadataPath = path.join(current, 'package.json');
    if (fs.existsSync(metadataPath)) {
      const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
      if (metadata.name === name) return current;
    }
    current = path.dirname(current);
  }
  throw new Error(`Unable to locate package root for ${name}`);
}

function copyPackageFile(packageName, sourcePath, outputPath) {
  const source = path.join(packageDir(packageName), sourcePath);
  const output = path.join(vendorDir, outputPath);
  fs.copyFileSync(source, output);
}

for (const [packageName, sourcePath, outputPath] of assets) {
  copyPackageFile(packageName, sourcePath, outputPath);
}

for (const [packageName, sourcePath, outputPath] of licenses) {
  const source = path.join(packageDir(packageName), sourcePath);
  fs.copyFileSync(source, path.join(licenseDir, outputPath));
}

const fftReadme = fs.readFileSync(path.join(packageDir('fft.js'), 'README.md'), 'utf8');
const fftLicenseMarker = '#### LICENSE';
const fftLicenseStart = fftReadme.indexOf(fftLicenseMarker);
if (fftLicenseStart < 0) throw new Error('Unable to locate the fft.js license text');
fs.writeFileSync(
  path.join(licenseDir, 'fft.js-LICENSE.md'),
  `${fftReadme.slice(fftLicenseStart + fftLicenseMarker.length).trim()}\n`,
  'utf8'
);

buildSync({
  stdin: {
    contents: "import FFT from 'fft.js'; export default FFT;",
    resolveDir: rootDir,
    sourcefile: 'fft-entry.js',
    loader: 'js'
  },
  outfile: path.join(vendorDir, 'fft.esm.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['chrome126'],
  minify: true,
  legalComments: 'inline',
  banner: { js: '/* fft.js 4.0.4 (MIT) - generated by scripts/sync-vendor.js */' }
});

const packageNames = ['chart.js', 'hammerjs', 'chartjs-plugin-zoom', 'mqtt', 'fft.js'];
const versions = Object.fromEntries(packageNames.map((name) => {
  const metadata = JSON.parse(fs.readFileSync(path.join(packageDir(name), 'package.json'), 'utf8'));
  return [name, metadata.version];
}));

const outputFiles = [...assets.map(([, , outputPath]) => outputPath), 'fft.esm.js'];
const sha256 = Object.fromEntries(outputFiles.map((fileName) => {
  const contents = fs.readFileSync(path.join(vendorDir, fileName));
  return [fileName, crypto.createHash('sha256').update(contents).digest('hex')];
}));

fs.writeFileSync(
  path.join(vendorDir, 'manifest.json'),
  `${JSON.stringify({ generatedBy: 'scripts/sync-vendor.js', versions, sha256 }, null, 2)}\n`,
  'utf8'
);

console.log(`Synchronized ${outputFiles.length} local runtime dependencies in ${vendorDir}`);
